import numpy as np
from datetime import datetime, timezone, timedelta
import plotly.graph_objects as go

from minimalsimulation import create_empty_simulation
from observatories import add_observatories, propagate_observatories
from plotting_3d import plot_3d_scatter
from detector import makeDetector, appendDetector
from constants import DEGREE, ARCSEC, EARTH_RADIUS
from celestialbodies import add_celestial_bodies, celestial_update
from pointing import detectorPointingInitialize, update_detector_pointing
from propagation import add_satellites_from_tle, propagate_satellites

def demo_observatories_only() -> tuple:
    """
    Runs a demonstration placing 5 observatories on Earth with no satellites.
    Propagates through 5 time steps, showing pointing vectors.

    Returns:
        A tuple of Plotly figure objects.
    """
    sim_start_time = datetime(2025, 7, 27, 22, 27, 0, tzinfo=timezone.utc)
    sim_data = create_empty_simulation(sim_start_time)
    add_celestial_bodies(sim_data)

    # 5 Observatory locations: Mauna Kea, Paranal, La Palma, Siding Spring, Kitt Peak
    latitudes = np.array([19.8206, -24.6272, 28.7636, -31.2755, 31.9583])
    longitudes = np.array([-155.4681, -70.4042, -17.8947, 149.0673, -111.5967])
    altitudes = np.array([4205.0, 2635.0, 2396.0, 1165.0, 2096.0])
    labels = ["Mauna Kea", "Paranal", "La Palma", "Siding Spring", "Kitt Peak"]

    print("\n--- Generating 3D plots for Demo Observatories Only ---")
    
    add_observatories(
        sim_data=sim_data,
        num_observatories=5,
        latitudes=latitudes,
        longitudes=longitudes,
        altitudes=altitudes
    )

    # Add satellites
    add_satellites_from_tle(sim_data, "standard_tle.txt", 'satellites')

    # Associate each observatory and satellite with a proper sensor/detector
    num_obs = sim_data.counts.observatories
    obs_detector = makeDetector(
        n=num_obs, band="V", fov=10 * DEGREE, ifov=3 * ARCSEC, aper=1.0,
        category=['observatories'] * num_obs,
        asset_index=np.arange(num_obs, dtype=int)
    )
    
    num_sats = sim_data.counts.satellites
    sat_detector = makeDetector(
        n=num_sats, band="V", fov=10 * DEGREE, ifov=3 * ARCSEC, aper=1.0,
        category=['satellites'] * num_sats,
        asset_index=np.arange(num_sats, dtype=int)
    )

    sim_data.detector = obs_detector
    appendDetector(sim_data.detector, sat_detector)

    detectorPointingInitialize(sim_data, grid_points=400)

    figs = []
    current_time = sim_start_time

    for step in range(5):
        # Propagate observatories and satellites to current_time (Earth rotation)
        propagate_observatories(sim_data, current_time)
        propagate_satellites(sim_data, current_time)
        celestial_update(sim_data, current_time)
        
        positions = sim_data.observatories.position
        sat_positions = sim_data.satellites.position
        
        # Update pointing using the pointing algorithm for both
        update_detector_pointing(sim_data, sat_category='observatories')
        update_detector_pointing(sim_data, sat_category='satellites')

        # Plot observatories and satellites
        all_positions = np.vstack([positions, sat_positions])
        all_labels = labels + [f"Sat {i}" for i in range(num_sats)]

        fig = plot_3d_scatter(
            positions=all_positions,
            title=f"Step {step+1}: Observatories and Satellites at {current_time.isoformat()}",
            plot_time=current_time,
            labels=all_labels,
            marker_size=4,
            trace_name='Assets',
            marker_color='blue'
        )
        
        # Plot a red vector originating in each asset showing where the sensor is pointing
        vector_scale = 0.5 * EARTH_RADIUS
        for i in range(num_obs + num_sats):
            start_point = all_positions[i]
            pointing_vec = sim_data.detector.pointing[i]
            end_point = start_point + pointing_vec * vector_scale
            
            fig.add_trace(go.Scatter3d(
                x=[start_point[0], end_point[0]],
                y=[start_point[1], end_point[1]],
                z=[start_point[2], end_point[2]],
                mode='lines',
                line=dict(color='red', width=4),
                showlegend=False
            ))

        fig.add_annotation(
            text="Generated by: demo_observatories_only",
            xref="paper", yref="paper",
            x=0.5, y=1.01,
            showarrow=False,
            font=dict(size=10, color="gray"),
            xanchor="center", yanchor="bottom"
        )

        figs.append(fig)
        
        # Call print_simulation_state after the first plot
        if step == 0:
            from sim_report import print_simulation_state
            print_simulation_state(sim_data)
        
        # Propagate forward in time by 2 hours
        current_time += timedelta(hours=2)
        
    return tuple(figs)
